from enum import Enum

class TestWeighting(Enum):
    lANG_WEIGHTING = 30
    ISHIHARA_WEIGHTING = 30

    STEREOSCOPIC_VISION_WEIGHTING = 0
    VISUAL_DEPTH_PERCEPTION_WEIGHTING = 20
    VISUAL_PERCEPTION_OF_COLOR_WEIGHTING = 20
    VISUAL_FIELD_WEIGHTING = 0