# Generated by Django 3.1.12 on 2022-01-07 08:09

import classic_test.models.lang_ishihara_model
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LangIshiharaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(max_length=100)),
                ('type_test', models.CharField(max_length=10)),
                ('items_card', djongo.models.fields.ArrayField(model_container=classic_test.models.lang_ishihara_model.ItemsCard)),
            ],
        ),
    ]
