# Generated by Django 4.0.1 on 2022-01-12 05:36

import classic_test.models.lang_ishihara_model
import classic_test.models.lang_ishihara_results_model
import django.contrib.postgres.fields
from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsCard',
            fields=[
                ('item_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description_english', models.CharField(max_length=100)),
                ('description_spanish', models.CharField(max_length=100)),
                ('weighing', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsCardResult',
            fields=[
                ('item_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('correct_answer_spanish', models.CharField(max_length=100)),
                ('correct_answer_english', models.CharField(max_length=100)),
                ('value_correct_answer', models.FloatField()),
                ('value_result_answer', models.FloatField()),
                ('answer_correct', models.BooleanField()),
                ('incorrect_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultsDetail',
            fields=[
                ('id_test', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('card_test_name_spanish', models.CharField(blank=True, max_length=100)),
                ('card_test_name_english', models.CharField(blank=True, max_length=100)),
                ('observations', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('items_card', djongo.models.fields.ArrayField(model_container=classic_test.models.lang_ishihara_results_model.ItemsCardResult)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LangIshiharaResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_patient_tests', models.CharField(max_length=20)),
                ('type_test', models.CharField(max_length=10)),
                ('results', djongo.models.fields.ArrayField(model_container=classic_test.models.lang_ishihara_results_model.ResultsDetail)),
            ],
        ),
        migrations.CreateModel(
            name='LangIshiharaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test_spanish', models.CharField(max_length=100)),
                ('name_test_english', models.CharField(max_length=100)),
                ('type_test', models.CharField(max_length=10)),
                ('items_card', djongo.models.fields.ArrayField(model_container=classic_test.models.lang_ishihara_model.ItemsCard)),
            ],
        ),
        migrations.CreateModel(
            name='TitmusAnimals',
            fields=[
                ('animal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animal_name_spanish', models.CharField(max_length=200)),
                ('animal_name_english', models.CharField(max_length=200)),
                ('weighing', models.FloatField()),
                ('row', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
                ('is_correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TitmusCircles',
            fields=[
                ('cirles_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('circle_name_spanish', models.CharField(max_length=200)),
                ('circle_name_english', models.CharField(max_length=200)),
                ('weighing', models.FloatField()),
                ('num_figure', models.IntegerField()),
                ('is_correct', models.BooleanField()),
            ],
        ),
    ]
