# Generated by Django 4.0.1 on 2022-01-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='langishihararesult',
            old_name='id_ticket',
            new_name='id_ticket_patient_tests',
        ),
    ]
