# Generated by Django 4.0 on 2022-01-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='id_resource_parent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resources',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
