# Generated by Django 4.0.1 on 2022-01-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesProfile',
            fields=[
                ('id_resource_parent', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('id_resource', models.CharField(max_length=100)),
                ('page_name', models.CharField(max_length=100)),
                ('tab_name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
