# Generated by Django 4.0.1 on 2022-01-24 19:17

from django.db import migrations, models
import djongo.models.fields
import patients.models.medical_history


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(error_messages={'unique': 'patient_id already used'}, max_length=50, unique=True)),
                ('eyeglasses', djongo.models.fields.EmbeddedField(model_container=patients.models.medical_history.EyeglassesPatient)),
                ('diseases', djongo.models.fields.ArrayField(model_container=patients.models.medical_history.Diseases)),
            ],
        ),
    ]
